const json = {
    "weatherIcon": {
        "阳光明媚": "1d",
        "晴朗无云": "1d",
        "晴朗": "2d",
        "繁星点点": "1n",
        "局部多云": "3d",
        "多云": "3d",
        "大部晴朗": "2d",
        "大部多云": "4d",
        "雷阵雨": "8d",
        "冰雹": "50d",
        "细雨": "6d",
        "有雨": "6d",
        "阵雨": "5d",
        "雷暴雨": "8n",
        "局部雷暴雨": "8n",
        "局部阵雨": "8n",
        "雨夹冰雹": "10d",
        "雨": "6d",
        "烟雾": "12n",
        "有烟雾": "12n",
        "有霾": "13n",
        "雾霾": "13n",
        "阴霾": "13n",
        "薄雾": "12d", 
        "有雾": "13d", 
        "大雾": "13d", 
        "零星阵雪": "9d",
        "雨雪交加": "10d",
        "小阵雪": "9d", 
        "有雪": "9d", 
        "大雪": "11d", 
        "暴雪": "11d",
        "雪": "9d",
        "下雪": "9d",
        "刮风": "14d",
        "有风": "14d"
      },
      "weatherSF": {
        "阳光明媚": "sun.max.fill",
        "晴朗": "sun.max.fill",
        "晴朗无云": "sun.max.fill",
        "繁星点点": "moon.stars.fill",
        "局部多云": "cloud.sun.fill",
        "多云": "cloud.fill",
        "大部晴朗": "cloud.sun.fill",
        "大部多云": "cloud.sun.fill",
        "雷阵雨": "cloud.drizzle.fill",
        "冰雹": "cloud.drizzle.fill",
        "细雨": "cloud.drizzle.fill",
        "有雨": "cloud.rain.fill",
        "阵雨": "cloud.drizzle.fill",
        "局部阵雨": "cloud.drizzle.fill",
        "局部雷暴雨": "cloud.drizzle.fill",
        "雷暴雨": "cloud.drizzle.fill",
        "雨夹冰雹": "cloud.drizzle.fill",
        "雨": "cloud.drizzle.fill",
        "烟雾": "sun.haze.fill",
        "有霾": "sun.haze.fill",
        "雾霾": "sun.haze.fill",
        "阴霾": "sun.haze.fill",
        "薄雾": "sun.haze.fill", 
        "有雾": "sun.haze.fill", 
        "大雾": "sun.haze.fill", 
        "零星阵雪": "cloud.snow.fill",
        "雨雪交加": "cloud.snow.fill",
        "小阵雪": "cloud.snow.fill", 
        "有雪": "cloud.snow.fill", 
        "大雪": "cloud.snow.fill", 
        "暴雪": "cloud.snow.fill",
        "雪": "cloud.snow.fill",
        "下雪": "cloud.snow.fill",
        "刮风": "wind",
        "有风": "wind",
      }
  }
  const weatherDes = () => {
    return json;
  }
  
  module.exports = weatherDes;
