name: 'GitHub Actions pull'

on:
  push:
    branches: 
      - master
  schedule:
   - cron: '33 */6 * * *'
  workflow_dispatch:
  watch:
    types: started
jobs:
  GitHub_Actions:
    runs-on: ubuntu-latest
    steps:
      - name: set_time
        run: |
          cp /usr/share/zoneinfo/Asia/Shanghai /etc/localtime
          date
      - name: Checkout
        uses: actions/checkout@v2
      - name: "clone elecV2P"
        run: |
          rm -rf elecV2P
          git clone https://github.com/elecV2/elecV2P.git
          cd elecV2P 
          rm -rf .git 
          echo "=================="
          cd ..
          echo "# 更新时间⌚️ 
          > $(date +%Y%m%d-%H:%M)" > README.md
          
      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests==2.22.0       
      - name: Update host
        run: |
          python web/socket_query.py
          mv hosts.txt web/hosts.txt
          
      - name: Commit files
        run: |
          pwd
          ls
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add .
          git commit -m "$(date +%Y%m%d-%H:%M)" -a
      - name: 'Push changes'
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.TOKEN }}
